### ISSUE TITLE
tls_client_config

### ISSUE THREAD

**Issue by fwsGonzo** [Engil/ocaml-ctypes-inverted-stubs-tls-prototype#1]
Hey!

From the looks of it `tls_client_config` will internally use `open` and friends to read files etc. For an operating system that doesn't have synchronous filesystem and is therefore unable or unwilling to support POSIX interfaces, this means we will have to patch that API function ourselves.

Is there any way you can modify it (or add an alternative) to, say, take `(void*, length)` or two strings?

Is this on your todo? Ref:
https://github.com/Engil/ocaml-ctypes-inverted-stubs-tls-prototype/blob/master/lib/bindings.ml#L82

**Comment by yallop** [comment]
> Is there any way you can modify it (or add an alternative) to, say, take (void*, length) or two strings?

Yes, we're planning to make this change, and move the POSIX bits into an outer layer.

**Comment by fwsGonzo** [comment]
That's good to hear. Really liking the simplicity of the API so far.
